### ISSUE TITLE
Actively developed?

### ISSUE THREAD

**Issue by refi64** [mgreter/sourcemap.cpp#1]
I'm trying to embed libsass (oh wow, how fitting ;) in my C++ application and have run into the issue of error messages. I figured this library would be perfect! However, it does worry me a bit that there hasn't been any activity whatsoever for almost three years.

Is this still actively developed? Or did it just reach a point of being "good enough"?

**Comment by mgreter** [comment]
No, this is not "actively" maintained, since I have a) too much on the plate and b) have decided to step back a bit on my OSS contributions. After all this was merely a hacky way to get something going. As always, PRs are very welcome if somebody wants to step up! Thanks for your understanding!
